changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Fixed
      labels:
        - bug
    - title: Added
      labels:
        - enhancement
    - title: Changed
      labels:
        - "*"